apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx2
  name: nginx2
spec:
  ports:
  - port: 82
    nodePort: 32000
    targetPort: 82
  selector:
    app: nginx2
  type: NodePort
status:
  loadBalancer: {}
