allowVolumeExpansion: false
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  managedFields:
  - apiVersion: storage.k8s.io/v1
    manager: agent
  name: test1
parameters:
  encrypted: "true"
  fsType: ext4
  iopsPerGB: "0"
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate